import React, { useState } from 'react';
import {
  View,
  Text,
  StyleSheet,
  TouchableOpacity,
  FlatList,
  ActivityIndicator,
  ScrollView,
  Platform,
  Alert,
} from 'react-native';
import Clipboard from '@react-native-clipboard/clipboard';
import type {
  ProviderSettings,
  ExtractedMetadataList,
  ProofData,
  FlowState,
  NetworkEvent,
} from '../../../src';

function serializeBigInt(_key: string, value: any) {
  if (typeof value === 'bigint') {
    return value.toString();
  }
  return value;
}

interface CombinedScreenProps {
  items: ExtractedMetadataList[];
  onGoBack: () => void;
  generateProof: (
    providerCfg: ProviderSettings,
    payload: NetworkEvent,
    intentHash: string,
    itemIndex?: number
  ) => Promise<ProofData[]>;
  proofData: ProofData[];
  flowState: FlowState;
  authError: Error | null;
  zkp2pProviderConfig: ProviderSettings | null;
  interceptedPayload: NetworkEvent | null;
}

export const ProofScreen: React.FC<CombinedScreenProps> = ({
  items,
  onGoBack,
  generateProof,
  proofData,
  flowState,
  authError,
  zkp2pProviderConfig,
  interceptedPayload,
}) => {
  const [selectedItemForProof, setSelectedItemForProof] =
    useState<ExtractedMetadataList | null>(null);
  const [copiedProof, setCopiedProof] = useState<string | null>(null);

  // Detect if this is an auto-generated proof
  const isAutoGenerated =
    proofData &&
    proofData.length > 0 &&
    !selectedItemForProof &&
    (flowState === 'authenticated' ||
      flowState === 'proofGeneratedSuccess' ||
      flowState === 'idle');
  const isAutoGenerating =
    !selectedItemForProof && flowState === 'proofGenerating';

  const copyProofToClipboard = (proof: any, proofId: string) => {
    // If we have multiple proofs, copy all of them
    const proofString =
      proofData && proofData.length > 1
        ? JSON.stringify(
            proofData.map((pd) => pd.proof),
            serializeBigInt,
            2
          )
        : JSON.stringify(proof, serializeBigInt, 2);

    Clipboard.setString(proofString);
    setCopiedProof(proofId);

    // Show alert
    const message =
      proofData && proofData.length > 1
        ? `${proofData.length} proofs copied to clipboard!`
        : 'Proof copied to clipboard!';

    Alert.alert('Success', message, [{ text: 'OK', onPress: () => {} }]);

    // Clear the copied state after 3 seconds
    setTimeout(() => {
      setCopiedProof(null);
    }, 3000);
  };

  const handleItemPress = async (item: ExtractedMetadataList) => {
    if (!zkp2pProviderConfig || !generateProof || !interceptedPayload) {
      console.error(
        '[ProofScreen] Missing provider config or generateProof function via props.'
      );
      return;
    }
    setSelectedItemForProof(item);
    try {
      const intentHash =
        '0x0000000000000000000000000000000000000000000000000000000000000001';

      // generateProof now always returns an array
      const proofs = await generateProof(
        zkp2pProviderConfig,
        interceptedPayload,
        intentHash,
        item.originalIndex
      );

      if (proofs.length > 1) {
        console.log(
          `[ProofScreen] Generated ${proofs.length} proofs (including additional proofs)`
        );
      } else {
        console.log('[ProofScreen] Generated single proof');
      }
    } catch (err) {
      console.error('[ProofScreen] Error calling generateProof:', err);
    }
  };

  const renderTransactionItem = ({ item }: { item: ExtractedMetadataList }) => (
    <TouchableOpacity
      style={[
        styles.transactionItem,
        selectedItemForProof &&
          item.originalIndex === selectedItemForProof.originalIndex &&
          styles.transactionItemHighlighted,
      ]}
      onPress={() => handleItemPress(item)}
    >
      {Object.entries(item).map(([key, value]) => {
        if (key === 'hidden' || key === 'originalIndex') return null;
        return (
          <Text key={key} style={styles.transactionDetailText}>
            <Text style={styles.transactionDetailKey}>{key}: </Text>
            {String(value)}
          </Text>
        );
      })}
      {selectedItemForProof &&
        selectedItemForProof.originalIndex === item.originalIndex &&
        flowState === 'proofGenerating' && (
          <ActivityIndicator
            size="small"
            color="#007AFF"
            style={styles.activityIndicatorInItem}
          />
        )}
      {isAutoGenerated && item.originalIndex === 0 && (
        <Text style={styles.autoGeneratedLabel}>✓ Auto-generated proof</Text>
      )}
    </TouchableOpacity>
  );

  const isGeneratingProofForSelectedItem =
    selectedItemForProof && flowState === 'proofGenerating';

  const proofSuccessfullyGeneratedForSelectedItem =
    selectedItemForProof &&
    (flowState === 'authenticated' ||
      flowState === 'proofGeneratedSuccess' ||
      flowState === 'idle') &&
    proofData &&
    proofData.length > 0;

  const proofFailedForSelectedItem =
    selectedItemForProof && flowState === 'proofGeneratedFailure' && authError;

  return (
    <View style={styles.container}>
      <View style={styles.headerContainer}>
        <TouchableOpacity onPress={onGoBack} style={styles.backButton}>
          <Text style={styles.backButtonText}>‹ Back</Text>
        </TouchableOpacity>
        <Text style={styles.title}>Transactions & Proof</Text>
      </View>

      <FlatList
        data={items}
        renderItem={renderTransactionItem}
        keyExtractor={(item, index) =>
          item.originalIndex?.toString() || index.toString()
        }
        ListHeaderComponent={
          <>
            {isAutoGenerated && (
              <View style={styles.autoGeneratedNotice}>
                <Text style={styles.autoGeneratedTitle}>
                  ✅ Proof Auto-Generated Successfully!
                </Text>
                <Text style={styles.autoGeneratedSubtext}>
                  The proof for the first transaction was generated
                  automatically. You can still select other transactions to
                  generate proofs manually.
                </Text>
              </View>
            )}
            {isAutoGenerating && (
              <View style={styles.autoGeneratingNotice}>
                <ActivityIndicator size="small" color="#007AFF" />
                <Text style={styles.autoGeneratingText}>
                  Auto-generating proof for the first transaction...
                </Text>
              </View>
            )}
            <Text style={styles.listTitle}>
              {isAutoGenerated
                ? 'Transactions (first item has auto-generated proof):'
                : isAutoGenerating
                  ? 'Auto-generating proof...'
                  : 'Select an Item:'}
            </Text>
          </>
        }
        ListEmptyComponent={
          <Text style={styles.emptyListText}>No transactions found.</Text>
        }
        contentContainerStyle={styles.listContentContainer}
      />

      {selectedItemForProof && (
        <View style={styles.proofSectionContainer}>
          <Text style={styles.proofSectionTitle}>
            Proof Status for Item (Index: {selectedItemForProof.originalIndex})
          </Text>
          {isGeneratingProofForSelectedItem && (
            <View style={styles.card}>
              <ActivityIndicator size="large" color="#007AFF" />
              <Text style={styles.statusText}>
                Generating proof, please wait...
              </Text>
            </View>
          )}
          {proofSuccessfullyGeneratedForSelectedItem && (
            <View style={styles.card}>
              <Text style={styles.resultTitle}>
                {proofData && proofData.length > 1
                  ? `${proofData.length} Proofs Generated Successfully!`
                  : 'Proof Generated Successfully!'}
              </Text>
              <ScrollView style={styles.resultScrollView}>
                <Text style={styles.resultText}>
                  {proofData && proofData.length > 0
                    ? proofData
                        .map(
                          (pd, index) =>
                            `=== Proof ${index + 1} ===\n${JSON.stringify(pd.proof, serializeBigInt, 2)}`
                        )
                        .join('\n\n')
                    : 'No proof data available'}
                </Text>
              </ScrollView>
              <TouchableOpacity
                style={[
                  styles.copyButton,
                  copiedProof ===
                    `manual-${selectedItemForProof.originalIndex}` &&
                    styles.copiedButton,
                ]}
                onPress={() =>
                  copyProofToClipboard(
                    proofData?.[0]?.proof,
                    `manual-${selectedItemForProof.originalIndex}`
                  )
                }
              >
                <Text style={styles.copyButtonText}>
                  {copiedProof ===
                  `manual-${selectedItemForProof.originalIndex}`
                    ? '✓ Copied!'
                    : 'Copy Proof'}
                </Text>
              </TouchableOpacity>
            </View>
          )}
          {proofFailedForSelectedItem && (
            <View style={styles.card}>
              <Text style={styles.errorTitle}>Proof Generation Failed</Text>
              <Text style={styles.errorText}>{authError?.message}</Text>
            </View>
          )}
          {authError &&
            !proofFailedForSelectedItem &&
            flowState !== 'proofGenerating' &&
            flowState !== 'proofGeneratedSuccess' &&
            flowState !== 'idle' && (
              <View style={[styles.card, styles.generalErrorCard]}>
                <Text style={styles.errorTitle}>An Error Occurred</Text>
                <Text style={styles.errorText}>{authError.message}</Text>
              </View>
            )}
        </View>
      )}

      {/* Auto-generated proof section */}
      {(isAutoGenerating ||
        isAutoGenerated ||
        (flowState === 'proofGeneratedFailure' && !selectedItemForProof)) && (
        <View style={styles.proofSectionContainer}>
          <Text style={styles.proofSectionTitle}>
            Auto-Generated Proof (First Transaction)
          </Text>
          {isAutoGenerating && (
            <View style={styles.card}>
              <ActivityIndicator size="large" color="#007AFF" />
              <Text style={styles.statusText}>
                Auto-generating proof, please wait...
              </Text>
            </View>
          )}
          {isAutoGenerated && proofData && proofData.length > 0 && (
            <View style={styles.card}>
              <Text style={styles.resultTitle}>
                {proofData.length > 1
                  ? `${proofData.length} Proofs Generated Successfully!`
                  : 'Proof Generated Successfully!'}
              </Text>
              <ScrollView style={styles.resultScrollView}>
                <Text style={styles.resultText}>
                  {proofData && proofData.length > 0
                    ? proofData
                        .map(
                          (pd, index) =>
                            `=== Proof ${index + 1} ===\n${JSON.stringify(pd.proof, serializeBigInt, 2)}`
                        )
                        .join('\n\n')
                    : 'No proof data available'}
                </Text>
              </ScrollView>
              <TouchableOpacity
                style={[
                  styles.copyButton,
                  copiedProof === 'auto' && styles.copiedButton,
                ]}
                onPress={() =>
                  copyProofToClipboard(proofData?.[0]?.proof, 'auto')
                }
              >
                <Text style={styles.copyButtonText}>
                  {copiedProof === 'auto' ? '✓ Copied!' : 'Copy Proof'}
                </Text>
              </TouchableOpacity>
            </View>
          )}
          {flowState === 'proofGeneratedFailure' &&
            authError &&
            !selectedItemForProof && (
              <View style={styles.card}>
                <Text style={styles.errorTitle}>Auto-Generation Failed</Text>
                <Text style={styles.errorText}>{authError?.message}</Text>
              </View>
            )}
        </View>
      )}
    </View>
  );
};

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#f0f0f0' },
  headerContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 15,
    paddingVertical: 10,
    backgroundColor: '#FFFFFF',
    borderBottomWidth: 1,
    borderBottomColor: '#DDDDDD',
  },
  title: {
    fontSize: 18,
    fontWeight: 'bold',
    textAlign: 'center',
    flex: 1,
    marginLeft: -30,
  },
  backButton: { padding: 10, zIndex: 1 },
  backButtonText: { color: '#007AFF', fontSize: 17 },

  listContentContainer: { paddingHorizontal: 10, paddingBottom: 10 },
  listTitle: {
    fontSize: 16,
    fontWeight: '600',
    marginVertical: 15,
    marginLeft: 5,
    color: '#333',
  },
  emptyListText: {
    textAlign: 'center',
    marginTop: 50,
    fontSize: 16,
    color: 'grey',
  },

  transactionItem: {
    backgroundColor: 'white',
    padding: 15,
    borderRadius: 8,
    marginBottom: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.15,
    shadowRadius: 2,
    elevation: 2,
  },
  transactionItemHighlighted: {
    backgroundColor: '#E8F5E9',
    borderWidth: 2,
    borderColor: '#4CAF50',
  },
  transactionDetailText: { fontSize: 14, color: '#333', marginBottom: 3 },
  transactionDetailKey: { fontWeight: '500' },
  autoGeneratedLabel: {
    marginTop: 8,
    fontSize: 14,
    fontWeight: '600',
    color: '#4CAF50',
  },

  activityIndicatorInItem: {
    marginTop: 5,
  },

  proofSectionContainer: {
    padding: 10,
    borderTopWidth: 1,
    borderTopColor: '#DDDDDD',
    backgroundColor: '#f9f9f9',
  },
  proofSectionTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    marginBottom: 10,
    textAlign: 'center',
    color: '#222',
  },
  card: {
    backgroundColor: '#fff',
    borderRadius: 8,
    padding: 15,
    marginBottom: 10,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 1.5,
    elevation: 1.5,
  },
  statusText: { marginTop: 10, fontSize: 15, color: '#555' },
  resultTitle: {
    fontWeight: 'bold',
    marginBottom: 10,
    fontSize: 16,
    color: 'green',
  },
  resultScrollView: { maxHeight: 150, width: '100%' },
  resultText: {
    fontFamily: Platform.OS === 'ios' ? 'Menlo' : 'monospace',
    fontSize: 11,
    color: '#333',
  },

  errorTitle: {
    fontWeight: 'bold',
    marginBottom: 8,
    fontSize: 16,
    color: '#D8000C',
  },
  errorText: { fontSize: 14, color: '#D8000C', textAlign: 'center' },
  generalErrorCard: { backgroundColor: '#FFEBEE' },

  autoGeneratedNotice: {
    padding: 10,
    backgroundColor: '#E8F5E9',
    borderRadius: 8,
    marginBottom: 10,
  },
  autoGeneratedTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    marginBottom: 5,
    color: '#4CAF50',
  },
  autoGeneratedSubtext: {
    fontSize: 14,
    color: '#333',
  },

  autoGeneratingNotice: {
    padding: 10,
    backgroundColor: '#E8F5E9',
    borderRadius: 8,
    marginBottom: 10,
    flexDirection: 'row',
    alignItems: 'center',
  },
  autoGeneratingText: {
    marginLeft: 10,
    fontSize: 14,
    color: '#333',
  },
  copyButton: {
    marginTop: 10,
    paddingVertical: 8,
    paddingHorizontal: 16,
    backgroundColor: '#007AFF',
    borderRadius: 6,
    alignItems: 'center',
  },
  copiedButton: {
    backgroundColor: '#4CAF50',
  },
  copyButtonText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '600',
  },
});
